### ISSUE TITLE
Have site running, but no data in Blazegraph, fcrepo URLs get 404

### ISSUE THREAD

**Issue by kayakr** [Islandora-Devops/isle-site-template#16] opened 2023-08-23 03:25 UTC
I've built an initial site using the site template. During install I chose the Islandora 2 Starter Site profile. I can login as uid 1, give that account fedoraAdmin role, then add a repository item node and upload an original image. The thumbnail and service file images get generated ok, and the original image is in fcrepo. However:
* no data appears to be in Blazegraph, and blazegraph only has `kb` namespace by default. I manually added `islandora` namespace but this didn't seem to result in any data being stored in blazegraph
* The fcrepo URL visible on repository item node, e.g. https://fcrepo.islandora.dev/fcrepo/rest/62/8b/f9/d9/628bf9d9-b885-474b-8330-e88691788c0f gives a 404

**Comment by kayakr** [comment] 2023-08-23 22:43
Hmm, curious. Now that I manually added `islandora` namespace, I'm seeing recently add nodes in Blazegraph. Also, I'm now seeing fcrepo data for nodes (i.e. the UUID URLs are now resolving, for more recently added items, but not for the first couple of items I added).

**Comment by joecorall** [comment] 2023-10-11 14:34
Looks like the `cURL` commands [isle-dc used to get the namespace configured](https://github.com/Islandora-Devops/isle-buildkit/blob/main/drupal/rootfs/etc/islandora/utilities.sh#L746-L747) aren't running on startup.

**Comment by nigelgbanks** [comment] 2023-10-19 18:02
This is the installation script: 

https://github.com/Islandora-Devops/isle-site-template/blob/main/drupal/rootfs/etc/s6-overlay/scripts/install.sh

This line is configuring Blazegraph for the "default" site:

https://github.com/Islandora-Devops/isle-site-template/blob/b5f9ca30405a458b0301da7003b04129edda8b3a/drupal/rootfs/etc/s6-overlay/scripts/install.sh#L30

This is the functions' implementation:

https://github.com/Islandora-Devops/isle-buildkit/blob/20ce60742bf65341613d3c867fc505cbeb328efa/drupal/rootfs/etc/islandora/utilities.sh#L751-L755

And:

https://github.com/Islandora-Devops/isle-buildkit/blob/20ce60742bf65341613d3c867fc505cbeb328efa/drupal/rootfs/etc/islandora/utilities.sh#L731-L748

So the environment variable `DRUPAL_DEFAULT_TRIPLESTORE_NAMESPACE` defined here:

https://github.com/Islandora-Devops/isle-buildkit/blob/20ce60742bf65341613d3c867fc505cbeb328efa/drupal/Dockerfile#L62

Should be created as a namespace.

**Comment by nigelgbanks** [comment] 2023-10-19 18:58
I can't seem to reproduce the issue.

<img width="1112" alt="Screenshot 2023-10-19 at 20 23 40" src="https://github.com/Islandora-Devops/isle-site-template/assets/487373/bc8efacf-088a-4c46-a6e4-a130098d685d">

<img width="988" alt="Screenshot 2023-10-19 at 20 56 05" src="https://github.com/Islandora-Devops/isle-site-template/assets/487373/5b8776c0-4a4b-462b-91a5-406327686992">

**Comment by nigelgbanks** [comment] 2023-10-19 18:58
@kayakr can you provide additional steps to reproduce? Starting from a new site?

**Comment by nigelgbanks** [comment] 2024-04-02 16:40
No additional steps provided closing for now.

**Closed by nigelgbanks** 2024-04-02 16:40 UTC
