### ISSUE TITLE
setup.sh failing on Ubuntu 24.04

### ISSUE THREAD

**Issue by joshdentremont** [Islandora-Devops/isle-site-template#46] opened 2024-07-15 19:26 UTC
Not my issue, but https://islandora.slack.com/archives/CM6F4C4VA/p1721069130479709?thread_ts=1719794457.302669&cid=CM6F4C4VA

> it looks like the automatic setup.sh script for isle-site-template is broken on Ubuntu 24.04. docker compose --profile dev build was unsuccessful and the setup.sh could not generate all of the secrets. The manual instructions seem to be working

**Comment by joshdentremont** [comment] 2024-07-16 13:42
Just tested it on my mac and it works fine.

**Comment by Natkeeran** [comment] 2024-07-24 15:54
cannot reproduce this on Ubuntu 22.04.

**Comment by seth-shaw-asu** [comment] 2024-11-06 18:18
Discussed in the Tech Call today. @nigelgbanks and @rosiel (not present) were noted as users of the code server. @Natkeeran mentioned others have used it for debugging PHP issues. It might be good to keep it around _if_ someone can update that setup script to address this issue.

**Comment by nigelgbanks** [comment] 2024-11-06 18:47
I tried looking through the chat and I didn't really see how SSH_AUTH_SOCK affects `generate-secrets.sh`, so I tested locally by removing the environment variable and I noticed that it had no effect. 

Though I've observed that `tr` in the script behaves different on OSX, so I'll send up a pull for that.

**Comment by joecorall** [comment] 2024-11-06 21:01
@nigelgbanks - [this docker compose override](https://github.com/Islandora-Devops/isle-site-template/blob/main/docker-compose.linux.yml) requires the environment variable. When it's not set on linux, the script fails here: https://github.com/Islandora-Devops/isle-site-template/blob/main/generate-secrets.sh#L52

**Comment by nigelgbanks** [comment] 2024-11-06 22:18
Ah I see, for me on Ubuntu 24.04 this is the output.

```
WARN[0000] The "SSH_AUTH_SOCK" variable is not set. Defaulting to a blank string. 
invalid spec: ::Z: empty section between colons
```

The failure comes from the specified bind mount options mounting no location. I think I can put a fix for this in.

**Comment by nigelgbanks** [comment] 2024-11-06 22:26
This fixes it: https://github.com/Islandora-Devops/isle-site-template/pull/73

**Comment by nigelgbanks** [comment] 2024-11-06 22:30
As to for this:

> My question for @rosiel and @nigelgbanks is whether they find it's a better developer experience than editing Drupal code from the host system.

For me, very much so. I don't have a license for PHP Storm or the like, I don't even have PHP installed on my host system. Something like code server allows me to get in and write something with intellisense, xDebug, etc. Also, editing in the container avoids numerous problems with file permissions being different on the host, for example when doing development from Windows.

**Comment by nigelgbanks** [comment] 2024-11-06 22:33
> @Natkeeran - if there are debugging libraries like xdebug we want to enable, that could be done without forcing an IDE choice on developers.

It's not forced, it's just an easy to start with default. This is a template and when forking you're free to remove the IDE, Fedora or whatever.  Especially for those folks that are not primarily developers, and do not maintain their own setup on their host system.

**Comment by nigelgbanks** [comment] 2024-11-07 11:37
> I think folks who are primarily developers is who I have in mind when talking about this. Having a different IDE when modifying code running in the site template I find much to be wanting. Most Drupal developers are working on many sites, so having one site that's special in this way I think will cause head scratching.

I see your point. Though when I've done talks at IslandoraCon, there is often a group of non-developers wanting to learn a thing or two, and it's been useful, especially in a group setting.

> I would argue it's a difficult to start with default for most Drupal developers. The most popular local development options for Drupal (e.g. [ddev](https://ddev.com/)) use the host IDE.

By the way, you can use your host IDE with the current setup (or at least you could at one point, I don't have PHPStorm to test anymore). The `code-server` container has SSH and you can connect to it with your host IDE as a remote target and not use the `code-server` in the browser. 

By all means though feel free to raise a pull request adding support for `ddev`

**Comment by joecorall** [comment] 2024-11-12 17:42
Going to close this, but after reviewing the issues in this repo also want to link https://github.com/Islandora-Devops/isle-site-template/issues/13 here for [the discussion we had around the codeserver in this issue](https://github.com/Islandora-Devops/isle-site-template/issues/46#issuecomment-2459490719)

**Closed by joecorall** 2024-11-12 17:42 UTC
